FROM mcr.microsoft.com/devcontainers/base:ubuntu
RUN apt-get update
RUN apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
RUN rm -rf /var/lib/apt/lists/*
